/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface FlProgramCard {
    'background': string;
    'destinationName': string;
    'programName': string;
    'summary': string;
  }
  interface FlProgramCardAttributes extends StencilHTMLAttributes {
    'background'?: string;
    'destinationName'?: string;
    'programName'?: string;
    'summary'?: string;
  }

  interface FlProgramDetail {}
  interface FlProgramDetailAttributes extends StencilHTMLAttributes {}

  interface FlProgramList {
    'title': string;
  }
  interface FlProgramListAttributes extends StencilHTMLAttributes {
    'title'?: string;
  }

  interface FlProgramRating {}
  interface FlProgramRatingAttributes extends StencilHTMLAttributes {}

  interface FlProgramSliders {}
  interface FlProgramSlidersAttributes extends StencilHTMLAttributes {}

  interface FlRegister {
    'cleanDatabase': () => void;
    'loadPrograms': () => void;
    'sync': boolean;
    'syncData': () => void;
  }
  interface FlRegisterAttributes extends StencilHTMLAttributes {
    'sync'?: boolean;
  }

  interface FlTermsandconditions {}
  interface FlTermsandconditionsAttributes extends StencilHTMLAttributes {}

  interface MyComponent {}
  interface MyComponentAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'FlProgramCard': Components.FlProgramCard;
    'FlProgramDetail': Components.FlProgramDetail;
    'FlProgramList': Components.FlProgramList;
    'FlProgramRating': Components.FlProgramRating;
    'FlProgramSliders': Components.FlProgramSliders;
    'FlRegister': Components.FlRegister;
    'FlTermsandconditions': Components.FlTermsandconditions;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'fl-program-card': Components.FlProgramCardAttributes;
    'fl-program-detail': Components.FlProgramDetailAttributes;
    'fl-program-list': Components.FlProgramListAttributes;
    'fl-program-rating': Components.FlProgramRatingAttributes;
    'fl-program-sliders': Components.FlProgramSlidersAttributes;
    'fl-register': Components.FlRegisterAttributes;
    'fl-termsandconditions': Components.FlTermsandconditionsAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLFlProgramCardElement extends Components.FlProgramCard, HTMLStencilElement {}
  var HTMLFlProgramCardElement: {
    prototype: HTMLFlProgramCardElement;
    new (): HTMLFlProgramCardElement;
  };

  interface HTMLFlProgramDetailElement extends Components.FlProgramDetail, HTMLStencilElement {}
  var HTMLFlProgramDetailElement: {
    prototype: HTMLFlProgramDetailElement;
    new (): HTMLFlProgramDetailElement;
  };

  interface HTMLFlProgramListElement extends Components.FlProgramList, HTMLStencilElement {}
  var HTMLFlProgramListElement: {
    prototype: HTMLFlProgramListElement;
    new (): HTMLFlProgramListElement;
  };

  interface HTMLFlProgramRatingElement extends Components.FlProgramRating, HTMLStencilElement {}
  var HTMLFlProgramRatingElement: {
    prototype: HTMLFlProgramRatingElement;
    new (): HTMLFlProgramRatingElement;
  };

  interface HTMLFlProgramSlidersElement extends Components.FlProgramSliders, HTMLStencilElement {}
  var HTMLFlProgramSlidersElement: {
    prototype: HTMLFlProgramSlidersElement;
    new (): HTMLFlProgramSlidersElement;
  };

  interface HTMLFlRegisterElement extends Components.FlRegister, HTMLStencilElement {}
  var HTMLFlRegisterElement: {
    prototype: HTMLFlRegisterElement;
    new (): HTMLFlRegisterElement;
  };

  interface HTMLFlTermsandconditionsElement extends Components.FlTermsandconditions, HTMLStencilElement {}
  var HTMLFlTermsandconditionsElement: {
    prototype: HTMLFlTermsandconditionsElement;
    new (): HTMLFlTermsandconditionsElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'fl-program-card': HTMLFlProgramCardElement
    'fl-program-detail': HTMLFlProgramDetailElement
    'fl-program-list': HTMLFlProgramListElement
    'fl-program-rating': HTMLFlProgramRatingElement
    'fl-program-sliders': HTMLFlProgramSlidersElement
    'fl-register': HTMLFlRegisterElement
    'fl-termsandconditions': HTMLFlTermsandconditionsElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'fl-program-card': HTMLFlProgramCardElement;
    'fl-program-detail': HTMLFlProgramDetailElement;
    'fl-program-list': HTMLFlProgramListElement;
    'fl-program-rating': HTMLFlProgramRatingElement;
    'fl-program-sliders': HTMLFlProgramSlidersElement;
    'fl-register': HTMLFlRegisterElement;
    'fl-termsandconditions': HTMLFlTermsandconditionsElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
