/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface FlProgramCard {}
  interface FlProgramCardAttributes extends StencilHTMLAttributes {}

  interface FlProgramDetail {}
  interface FlProgramDetailAttributes extends StencilHTMLAttributes {}

  interface FlProgramList {}
  interface FlProgramListAttributes extends StencilHTMLAttributes {}

  interface MyComponent {}
  interface MyComponentAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'FlProgramCard': Components.FlProgramCard;
    'FlProgramDetail': Components.FlProgramDetail;
    'FlProgramList': Components.FlProgramList;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'fl-program-card': Components.FlProgramCardAttributes;
    'fl-program-detail': Components.FlProgramDetailAttributes;
    'fl-program-list': Components.FlProgramListAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLFlProgramCardElement extends Components.FlProgramCard, HTMLStencilElement {}
  var HTMLFlProgramCardElement: {
    prototype: HTMLFlProgramCardElement;
    new (): HTMLFlProgramCardElement;
  };

  interface HTMLFlProgramDetailElement extends Components.FlProgramDetail, HTMLStencilElement {}
  var HTMLFlProgramDetailElement: {
    prototype: HTMLFlProgramDetailElement;
    new (): HTMLFlProgramDetailElement;
  };

  interface HTMLFlProgramListElement extends Components.FlProgramList, HTMLStencilElement {}
  var HTMLFlProgramListElement: {
    prototype: HTMLFlProgramListElement;
    new (): HTMLFlProgramListElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'fl-program-card': HTMLFlProgramCardElement
    'fl-program-detail': HTMLFlProgramDetailElement
    'fl-program-list': HTMLFlProgramListElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'fl-program-card': HTMLFlProgramCardElement;
    'fl-program-detail': HTMLFlProgramDetailElement;
    'fl-program-list': HTMLFlProgramListElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
